<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>
  <ItemGroup>
      <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.5.3" />
      <PackageVersion Include="Aspire.Hosting" Version="13.5.3" />
  </ItemGroup>
</Project>
